name: 'coba workflow'
on: [push]
jobs:
  liat-versi-pm2:
   runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g pm2
      - run: pm2 -v
